# Generated by Django 3.2.6 on 2021-09-27 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_fbmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasksmodel',
            old_name='tasks',
            new_name='task',
        ),
    ]
