# Generated by Django 3.2.6 on 2021-09-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_rename_tasks_tasksmodel_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksmodel',
            name='task',
            field=models.CharField(max_length=150),
        ),
    ]
