# Generated by Django 3.2.6 on 2021-09-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0011_tasksmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbmodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
