# Generated by Django 3.2.6 on 2021-09-29 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0012_alter_fbmodel_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FbModel',
            new_name='FeedbackModel',
        ),
    ]
